name: golden-ratio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - ffmpeg
  - texlive-core
  - sox
  - pandoc
  - pip:
    - manim
    - numpy
    - scipy
    - colour
